FROM golang:1.11 as builder
RUN wget https://www.foundationdb.org/downloads/5.2.5/ubuntu/installers/foundationdb-clients_5.2.5-1_amd64.deb && dpkg -i foundationdb-clients_5.2.5-1_amd64.deb
WORKDIR /go/src/github.com/matterinc/PlasmaBlockCreator/
COPY . .
EXPOSE 3001
RUN cd cmd/utxoLister/ && go build -o app .

FROM ubuntu:18.04
RUN apt update && apt install -y wget
RUN wget https://www.foundationdb.org/downloads/5.2.5/ubuntu/installers/foundationdb-clients_5.2.5-1_amd64.deb && dpkg -i foundationdb-clients_5.2.5-1_amd64.deb
WORKDIR /root/
COPY --from=builder /go/src/github.com/matterinc/PlasmaBlockCreator/cmd/utxoLister/app .
CMD ["./app"]  