FROM golang:1.10.3 as builder
RUN wget https://www.foundationdb.org/downloads/5.2.5/ubuntu/installers/foundationdb-clients_5.2.5-1_amd64.deb && dpkg -i foundationdb-clients_5.2.5-1_amd64.deb
run wget https://www.foundationdb.org/downloads/5.2.5/ubuntu/installers/foundationdb-server_5.2.5-1_amd64.deb && dpkg -i foundationdb-server_5.2.5-1_amd64.deb

RUN curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
WORKDIR /go/src/github.com/shamatar/go-plasma/
COPY . .
#RUN go get -d -v
#RUN dep ensure -v
#RUN ls
#RUN cd ./vendor/github.com/matterinc/PlasmaCommons/crypto/secp256k1/
#RUN ls
#RUN rm -rf secp256k1
#RUN git clone https://github.com/bitcoin-core/secp256k1.git
#RUN ls
#RUN cd secp256k1
#RUN ls
#RUN cd ..
#RUN cd ../../../../../../
RUN curl -sL https://deb.nodesource.com/setup_10.x | bash -
RUN apt-get install -y -qq nodejs
#RUN cd redisPrep && npm install && node prepareRedis.js && cd ..
CMD ["bash", "initRedisAndRun.sh"]

#FROM ubuntu
#RUN apk --no-cache add ca-certificates
#RUN apt update && apt install -y curl wget
#RUN wget https://www.foundationdb.org/downloads/5.2.5/ubuntu/installers/foundationdb-clients_5.2.5-1_amd64.deb && dpkg -i foundationdb-clients_5.2.5-1_amd64.deb
#RUN mkdir /lib64 && ln -s /lib/libc.musl-x86_64.so.1 /lib64/ld-linux-x86-64.so.2
#WORKDIR /root/
#COPY --from=builder /go/src/github.com/shamatar/go-plasma/go-plasma .
#COPY fdb.cluster /etc/foundationdb/fdb.cluster
#EXPOSE 3001
#CMD ["/root/go-plasma"]
# CMD ["ln", "-ls"]
